### ISSUE TITLE
Great theme

### ISSUE THREAD

**Issue by chlins** [kpitt/zed-theme-intellij-newui#1]
Thank you for this excellent theme. I'm delighted with it. Do you have plans to create a version of this theme for Visual Studio Code as well? I will be using both editors since there are features that Zed does not currently support. Having a consistent theme on both sides would be ideal.

**Comment by kpitt** [comment]
I don't have any immediate plans for a VS Code theme, because I just don't use it often enough anymore to justify the time and effort that it would require.

I did find a couple of themes on the Visual Studio Marketplace that seem to be based on the same color palette. I spot-checked a handful of common colors in their source repositories, but I haven't tried either of these myself, so I can't make any guarantees about how complete they are or how consistent the experience would be with this theme in Zed. Might be worth a try, though.

- [JetBrains New UI Dark Theme](https://marketplace.visualstudio.com/items?itemName=Qvist.jetbrains-new-ui-dark-theme)
- [JetBrains New Dark](https://marketplace.visualstudio.com/items?itemName=MoBalic.jetbrains-new-dark)
